// <auto-generated />
using System;
using Infraestrutura.Configuracoes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestrutura.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entidades.Entidades.Fornecedor", b =>
                {
                    b.Property<int>("CodigoFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_FORNECEDOR")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("CodigoFornecedor");

                    b.ToTable("FORNECEDOR");
                });

            modelBuilder.Entity("Entidades.Entidades.Produto", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_PRODUTO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodigoFornecedor")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO_FORNECEDOR");

                    b.Property<DateTime?>("DataFabricacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_FABRICACAO");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_VALIDADE");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int?>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("SITUACAO");

                    b.HasKey("CodigoProduto");

                    b.HasIndex("CodigoFornecedor");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Entidades.Entidades.Produto", b =>
                {
                    b.HasOne("Entidades.Entidades.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("CodigoFornecedor");

                    b.Navigation("Fornecedor");
                });
#pragma warning restore 612, 618
        }
    }
}
